#!/bin/sh

# Color Aliases
alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
alias diff="diff --color=auto"
alias ip="ip -color=auto"

# Dotfiles repo alias
alias config="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
alias configclean=\
	"/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME update-index --assume-unchanged README.md && rm README.md"
