#!/bin/sh

# Profile file runs on login

### DEFAULT PROGRAMS
export TERMINAL="xterm-256color"
export EDITOR="nvim"
export VISUAL="nvim"


### ENVIRONMENT VARIABLES
if [ -d "$HOME/.local/bin" ]; then
    export PATH="$HOME/.local/bin:$PATH"
fi
if [ -d "$HOME/Applications" ]; then
    export PATH="$HOME/Applications:$PATH"
fi

# XDG Base Directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export HISTFILE="$XDG_STATE_HOME/zsh/history"
export LESSHISTFILE=-
