#!/bin/sh

# Temp at home set up, use external monitor only cause x230 TN panel is straining my eyes
xrandr | grep "HDMI1 disconnected" \
    || xrandr --output HDMI1 --primary --mode 1920x1080 --output LVDS1 --off
dunst &
picom &
